events {}

http {
    server {
        listen 8080;

        location = /loki/api/v1/push {
            proxy_pass http://loki-write:3100;
        }

        location ~ /loki/api/.* {
            proxy_pass http://loki-read:3100;
        }
    }
}
